pipeline {
  agent any
  stages {
    stage('Deploy') {
      steps {
        sh '''
docker build -t $IMAGE_NAME --build-arg port=$PORT -f deployment-script/jenkins.Dockerfile .
        '''
        sh 'docker stop $CONTAINER_NAME'
        sh 'docker rm $CONTAINER_NAME'
        sh 'docker run -p $PORT:$PORT -e PORT=$PORT --name $CONTAINER_NAME --restart unless-stopped --network host -d $IMAGE_NAME'
      }
    }
  }
  post {
    always {
      sh 'docker image prune -f -a'
    }
  }
  environment {
    FOLDER = '/var/www/pa11y-dashboard'
    CONTAINER_NAME = "pa11y_dashboard"
    REPO_NAME = "pa11y-dashboard"
    IMAGE_NAME = "fivejack/pa11y-dashboard"
    PORT = 3500
  }
}
